language: java

jdk: openjdk11

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "imousmoutis"
    token:
      secure: "dLmNPWqbRFbpv2BXyMF7DUtAZPKe9lLJH2ee5YU2NJ6EQ+EanuaBdx5N+1DK/w5BBiWoEE21pf6KyLEIYnuvzZCpC8ypZM/ju/3WWjkyJW5E7pDXaTBvqXiDjg0xKrLHH+JG305YG4sGz5Erv6Di3kOZuk0VyyQZ75CSiVPffKy76eWrUY8G0r1bh4qeRj5e1/K70BmXqLHRmBCKQugx4CldApEC13httTBmiKxyWi7x5SYkNJWpLswORuRYPiti//WKASFpOF3MmO6oeU1Wp/uZlfpFhSYO6Cu/0nOkRo3ctzk1w6vFFR5NkVWqWU+V6DOEqYtEW9jsKAlLPJ+9+6yGwxEKx6mKy8PLCufdjDLMMa3Q9ios1BZK1cEXwWyOEzgK60U76FbUUn7AE674KEXKfTOBElcdGR7jyilzSWvTI7bEibeRk1giIVoVLE7gDtEGqwkJo53I8cCGP8AlxH7HuVOSynjT4AfgZWiDAHJjR8fFeQc1pBxyAYxGKoeodBC0Czk0VIB7+P3um3TKPGnU87YGn+ZWBhwVVvMOvecxgO7aD9kiszNF7r2Kv3Y93dy9xJHLgmF7jI8uBaK6ZHSrYzsDbBEJ/oLe4ZO7qL7wy797e4MsqTzoXiJighDQZpQu1wCu0jO5nqsq58hBYOs4hHrXbS7sudHvsHAxlQo="

script:- ./mvnw clean install sonar:sonar -Dsonar.projectKey=imousmoutis_OpenWIS_CICD_Training_Ioannis 

notifications:
  email:
    recipients:
      secure: "Xj4uCB5lmBplulzrruuYOcrpp6Owp5chMCYCO/OaY0MQeLxYFyC5xUlL3sAMaZtNBuE03zGVjz2Mz021uQ5BTXaS7AzNQ70uOis0D5XuAoDiljWLOauV8BtRRD/QmLo7TqmnAr6YXh2Mjzlc1+DL7dDMlUHBBfopYZzliljZWl74XFrTMcnLuv5d21wOfPh//2/55sKukeaP2scS/qP+ZAIJ/nbD9x0pAv9QS0YgvXBE+ny9Cy/DJ0aiz1li0+aXifxQIzOKz9sWC8RV5YtWfdrLt1ff3vxWjvwO1vUno4ZlNLGD0LXN2D+GHy3JtRN1nydcvK7dmZDMCq2wmn+Yu5OhLMKhWBEnYOu+/XMQIKwsUBMjCH8YhmFkHz4VkxdOdtPzBSOdQAosMCk8Hk57Ok+1tbkyxl8lCZPHsX2pjStEXTMNa7CWf3ywHNJtFIE04+/DoZ9vQiTpfEionvHmMxXTXik7pWpiYgvYwcVgBFC34euTw8OR2Yw9ZhvGo8mat1nGTTh6FsSIfFrxGDV38GMGS0h3yA52yyw2J/DocMyekked4gVlPa1Nkb0q7rALVfWW2Mzia0zTs9cx7Ie77DeL7Lly+EpUEX1BTW7nlCGVCC8W+5qgC/WCoatmissjtskPjI6qIuq/b0s3hP/esMKIPCNa3eiG3YtaMU9E+lM="
  on_success: always
  on_failure: always