language: java

jdk: openjdk11

before_install:
- openssl aes-256-cbc -K $encrypted_8408ce87f49d_key -iv $encrypted_8408ce87f49d_iv -in ioannis_rsa.enc -out ioannis_rsa -d
- chmod +x mvnw
- eval "$(ssh-agent -s)"
- chmod 600 ioannis_rsa
- ssh-add ioannis_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

addons:
  sonarcloud:
    organization: imousmoutis
    token:
      secure: dLmNPWqbRFbpv2BXyMF7DUtAZPKe9lLJH2ee5YU2NJ6EQ+EanuaBdx5N+1DK/w5BBiWoEE21pf6KyLEIYnuvzZCpC8ypZM/ju/3WWjkyJW5E7pDXaTBvqXiDjg0xKrLHH+JG305YG4sGz5Erv6Di3kOZuk0VyyQZ75CSiVPffKy76eWrUY8G0r1bh4qeRj5e1/K70BmXqLHRmBCKQugx4CldApEC13httTBmiKxyWi7x5SYkNJWpLswORuRYPiti//WKASFpOF3MmO6oeU1Wp/uZlfpFhSYO6Cu/0nOkRo3ctzk1w6vFFR5NkVWqWU+V6DOEqYtEW9jsKAlLPJ+9+6yGwxEKx6mKy8PLCufdjDLMMa3Q9ios1BZK1cEXwWyOEzgK60U76FbUUn7AE674KEXKfTOBElcdGR7jyilzSWvTI7bEibeRk1giIVoVLE7gDtEGqwkJo53I8cCGP8AlxH7HuVOSynjT4AfgZWiDAHJjR8fFeQc1pBxyAYxGKoeodBC0Czk0VIB7+P3um3TKPGnU87YGn+ZWBhwVVvMOvecxgO7aD9kiszNF7r2Kv3Y93dy9xJHLgmF7jI8uBaK6ZHSrYzsDbBEJ/oLe4ZO7qL7wy797e4MsqTzoXiJighDQZpQu1wCu0jO5nqsq58hBYOs4hHrXbS7sudHvsHAxlQo=

script:
- "./mvnw clean install sonar:sonar -Dsonar.projectKey=imousmoutis_OpenWIS_CICD_Training_Ioannis"

deploy:
  - provider: script
    skip-cleanup: true
    script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/target/cicd-example-*.jar ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}    
    on:
      branch: master

  - provider: script
    skip-cleanup: true
    script: sh ${TRAVIS_BUILD_DIR}/remote_deploy.sh
    on:
      branch: master

notifications:
  email:
    recipients:
      secure: Xj4uCB5lmBplulzrruuYOcrpp6Owp5chMCYCO/OaY0MQeLxYFyC5xUlL3sAMaZtNBuE03zGVjz2Mz021uQ5BTXaS7AzNQ70uOis0D5XuAoDiljWLOauV8BtRRD/QmLo7TqmnAr6YXh2Mjzlc1+DL7dDMlUHBBfopYZzliljZWl74XFrTMcnLuv5d21wOfPh//2/55sKukeaP2scS/qP+ZAIJ/nbD9x0pAv9QS0YgvXBE+ny9Cy/DJ0aiz1li0+aXifxQIzOKz9sWC8RV5YtWfdrLt1ff3vxWjvwO1vUno4ZlNLGD0LXN2D+GHy3JtRN1nydcvK7dmZDMCq2wmn+Yu5OhLMKhWBEnYOu+/XMQIKwsUBMjCH8YhmFkHz4VkxdOdtPzBSOdQAosMCk8Hk57Ok+1tbkyxl8lCZPHsX2pjStEXTMNa7CWf3ywHNJtFIE04+/DoZ9vQiTpfEionvHmMxXTXik7pWpiYgvYwcVgBFC34euTw8OR2Yw9ZhvGo8mat1nGTTh6FsSIfFrxGDV38GMGS0h3yA52yyw2J/DocMyekked4gVlPa1Nkb0q7rALVfWW2Mzia0zTs9cx7Ie77DeL7Lly+EpUEX1BTW7nlCGVCC8W+5qgC/WCoatmissjtskPjI6qIuq/b0s3hP/esMKIPCNa3eiG3YtaMU9E+lM=
  on_success: always
  on_failure: always
env:
  global:
  - secure: cwxEi8KS6ez6fZXtCMfhwpjKPOh26y8Z5I+jaJ4RQTzNR+sfNKdx7IryQh9Qrvunuu6DX4Jdkja6lg2qWBIp3DnYOouipa1CU1cnP9EY+FNWFSlqC0o85izZ0g47WnujfvG2RYTSPlBtHwEXDsMlMeJhWcfveElLovugcBVewST2h4UfzVRKbecDkFuXptKjWXMR0ilbYUoCQ0W9qAbbOxrLLMDrsN0oqyV0DMUiYs2WCHA8eeFu/Zj+G0PrG/DxlMKBUNlROsO3LLuCv4RRHT4hmZUaY/Pvb3/Hd50TkA5qTZNLxwcxQQlv/woQO1QrSnKVudF96ghso4dZTXl40lld33UzUtCwDTvuoJt8cg4yss4DA5qsQ2vHh2xGHz9a2HyS2Z37rHsRYZOQQbEP8PJ3TXTz8CNY+Crhn0oKn/I5/8X0CwKzZdSAYS1e5hbMiZp7MxTq2KqlwXrw+bCIPW3qXsPl0UbtaZZq0f6ocCJEI0BlUVbJSVEkx0LwkVMUbaNXT7VseRoPHhGrgKBhVC1b9DYnQnrGXEy+cyWmPiHlRtsEb3ruyjX8KNzfxjqcBKQkEbGyuzjceTaT/VOlIhm6Wut/ybuuoOqGLEaYplzxwcI9MXPNtK7B7Cak1IF0B2wmqj0wBSQ/tfdWwz4xmS86XAISCGNjz87bFXVUOP4=
  - secure: nRbAvSzucqtuiNH5+ulzJuIGXy6GRQVk82+398Z7weZv4cVwXze7gMLWtGuh585cBJRkEJpNEk4akKc6RGRHjIYIjhgte+AGBRYBP6Pm8CGTTLtf0vgvm1qEshlDI/g/7Q8bim9M1mTEpmScHY6iHVDQnlwIXXG8PvWpHxCfCCw4UmUT5ciZSBOm9h6BaJdPKSlILCogsZArrbPgE58nX79y2lWdeOIp+uutHvHvlIDIkKxxRuWWqip5rvZYxURIMXFgQydczLZcviBFs/d/4nobtfsj7gY5jLGWOZWJLvh/cGNXdNalKItZd3xMaEhhsA0gs3mLNkR+wIVagGAoe6RRI7ZtgyFjzaaXZBvxK8BfYyndMmpyTza6FLHoFayEwFZg97Bwbt7l+u1lNhriBKFrpShY0GhfbvWot6NibdqRNBGpBTIRLqIsCLp/aIA3HAGI1r2l5UNLSpcL1k9e9SLoLvYG/Ouo+XyaQzqc6L1rHiy2a987joMyWZnVLZ7+MMD67rpa6xGfFnh6jVyHHoPG0UIRHblZT5uBo7seuXNyLJfmtR9BC8Y7cp2p7DsgJvzbm5CdwcAbkxCPucwrBbj/gWg03ODodLQkeu+nunSGIsSe7xeAOOopaKFFz3wG5P3Dxy0NYXDT2TGDVd8YW0diNbYyzM5WX/foeCfT52Q=
  - secure: Qv8gUruAfOkjuBfhu5EmcdBjS3ttY94C9/6iwSe/mfpSkUxz//WpnWLnkb2LUgbqr/tQb269q4Cq47HSYUjKNNRAU52t83jgPsgriKajPOO9LwcJWJLz5HUhRiGh1X8RQzyYF2MHq2sqEZp8jqlNq5MaMNTpT8BWTuV5pbNnE9j9QQzjkcfi8TDI6GbD24NK46ihMIKWJNC/lVGLZuF1WzYec3hQ8Zh4b4JjHQt0tw4cqrH4uiHtFRmJ9/AcLzMvxSrGd/hPgTtAjzW7pJFIDZsUzpsdiDiHgiwj8KvjwWSwbjM7/4O3SYYm6kmt/RvRQ439sp0vRELq21pXT7BoraibW9bUZm8MoO4BWhJt4wNxefM0ukHH0nseHMT5McjlI0is9eNf8rYFcni2YSUsAUJq0lyiSV1dCfeRex8MuWcoRZ+1/TvhrQdEcFtMpj8AGw+4m6IGVnYSL2NAc0jWyVg21pr4m5QytpbnYqG849oFq3+T0dGgvZuSKSsn0C6ntI7eh55BlCm/OtC9Sj/IGZ/qXw4Y0i9KFpF4sdvHBM8UlwZwua02XehmY/mvS/P+79GrfHzghEWUItFiVdAjSNxHy9CtiPvCJi6Noha9rcgeS+Onm+cHlGym1qZudqfdOh70QZcVWnG93/t/t9NPAgZgotO4krFhZ4So59wpjaw=
